language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
"pip install git+https://github.com/nwcell/psycopg2-windows.git@win64-py27#egg=psycopg2"