language: python

sudo: false

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TEST_TARGET=default
  allow_failures:
  - python: 3.6
    env: TEST_TARGET=coding_standards


before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update conda --yes
    - conda config --add channels conda-forge --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
    - source activate TEST
    - pip install --upgrade http://github.com/miguelcleon/django-admin-shortcuts/zipball/master

install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install odm2admin-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      python setup.py test;
    fi
  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      find . -type f -name "*.py" ! -name "base.py" | xargs flake8 --max-line-length=100 --ignore=E402 ;
    fi
