version: '3'

services:
  db:
    container_name: odm2admindb
    image: mdillon/postgis:9.5
    restart: always
    expose:
      - "5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  app:
    container_name: odm2adminapp
    image: odm2/odm2admin
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./settings:/ODM2-Admin/templatesAndSettings/settings